.\" genhydro - Hydrogen Drumkit Generator
.TH "genhydro" "8" ""  "Klaatu" ""
.SH "NAME"
genhydro \- Generate Hydrogen drumkit files from a directory of sounds
.SH "SYNOPSIS"
\fBgenhydro\fP
.SH "DESCRIPTION"
.PP 
\fBgenhydro\fP, is a tool that converts a directory of sounds into
Hydrogen drumkit files.
.PP
.SH USE CASE AND WORKFLOW
Change directory into the directory containing your sound files. Run
genhydro. Done.
.PP
.SH INSTALLATION
Copy genhydro.py to any executable path on your system.
.PP
.SH BUGS
.TP
There are many; currently genhydro is not a terribly robust
application. For example, its limitations are: you must be in the
directory you want to convert when genhydro is run, you cannot do
velocity detection or take advantage of many of Hydrogen's cool
drumkit features, it only works with flac files. 
.PP
.SH "AUTHORS"
.nf
Klaatu (klaatu@member.fsf.org)
.fi
